// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TransactionUpdate.DalLayer.Data;

#nullable disable

namespace TransactionUpdate.DalLayer.Migrations
{
    [DbContext(typeof(TransactionDbContext))]
    partial class TransactionDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.1");

            modelBuilder.Entity("TransactionUpdate.DalLayer.Model.TransactionModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<double>("Amount")
                        .HasColumnType("REAL");

                    b.Property<string>("DateTime")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Transactions");

                    b.HasData(
                        new
                        {
                            Id = 11,
                            Amount = 500.0,
                            DateTime = "2020-09-08'T'16:34:23Z",
                            Description = " Bank Deposit",
                            Status = "Completed"
                        },
                        new
                        {
                            Id = 10,
                            Amount = -20.0,
                            DateTime = "2021-09-08'T'09:02:23Z",
                            Description = "Transfer to James",
                            Status = "Pending"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
